import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import "./globals.css";

export const metadata: Metadata = {
  title: "Dekamond",
  description: "Generated by Dekamond app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className="antialiased"
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
